plugins:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/Copyright:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/NestedGroups:
  Max: 5